// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKOs_l2vekwZjXEV6h0obuJW9Eph-b7ik',
    appId: '1:683688744655:web:20a6b6745a72b7025389ba',
    messagingSenderId: '683688744655',
    projectId: 'foundone-42999',
    authDomain: 'foundone-42999.firebaseapp.com',
    storageBucket: 'foundone-42999.firebasestorage.app',
    measurementId: 'G-K3TTDCGFWR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2CDK52IxNOnTCsJb-cYV4iaXM-CMZ4zA',
    appId: '1:683688744655:android:e42497511d6288da5389ba',
    messagingSenderId: '683688744655',
    projectId: 'foundone-42999',
    storageBucket: 'foundone-42999.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXMuxG3vbS-ZUhq6NmhzU275zJu6SgB98',
    appId: '1:683688744655:ios:b4ce020425da5b6d5389ba',
    messagingSenderId: '683688744655',
    projectId: 'foundone-42999',
    storageBucket: 'foundone-42999.firebasestorage.app',
    iosBundleId: 'com.example.foundOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXMuxG3vbS-ZUhq6NmhzU275zJu6SgB98',
    appId: '1:683688744655:ios:b4ce020425da5b6d5389ba',
    messagingSenderId: '683688744655',
    projectId: 'foundone-42999',
    storageBucket: 'foundone-42999.firebasestorage.app',
    iosBundleId: 'com.example.foundOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKOs_l2vekwZjXEV6h0obuJW9Eph-b7ik',
    appId: '1:683688744655:web:ffbd32f47328cbaf5389ba',
    messagingSenderId: '683688744655',
    projectId: 'foundone-42999',
    authDomain: 'foundone-42999.firebaseapp.com',
    storageBucket: 'foundone-42999.firebasestorage.app',
    measurementId: 'G-Z2EN17SJMK',
  );
}
